### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheCrafter8000** [DerFrZocker/Fortress-Control#1]
I get this error when trying to start up on 1.17.1 paper

[13:50:31 ERROR]: Could not pass event WorldInitEvent to Fortress-Control v1.0.0
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_16_R2/CraftWorld
	at de.derfrzocker.fc.WorldHandler_v1_16_R2.onWorldLoad(WorldHandler_v1_16_R2.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-125]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-125]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-125]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:657) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:609) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-125]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_16_R2.CraftWorld
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146) ~[patched_1.17.1.jar:git-Paper-125]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-125]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	... 12 more
[13:50:33 ERROR]: Could not pass event WorldInitEvent to Fortress-Control v1.0.0
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_16_R2/CraftWorld
	at de.derfrzocker.fc.WorldHandler_v1_16_R2.onWorldLoad(WorldHandler_v1_16_R2.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-125]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-125]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-125]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:657) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:609) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-125]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[13:50:33 WARN]: Unable to find spawn biome
[13:50:34 ERROR]: Could not pass event WorldInitEvent to Fortress-Control v1.0.0
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_16_R2/CraftWorld
	at de.derfrzocker.fc.WorldHandler_v1_16_R2.onWorldLoad(WorldHandler_v1_16_R2.java:56) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.17.1.jar:git-Paper-125]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.17.1.jar:git-Paper-125]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.17.1.jar:git-Paper-125]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:657) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:609) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-125]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-125]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by DerFrZocker** [comment]
Plugin was updated 1.17.1 in version 1.1.0
